   list - nasted list
   boolean
   Maths - operations
   logical operations
   insert
   pop
   default data structure - dict,lib,list
   append
   
Day-2
  pandas
  datframes
  series
  indexing-i.loc
  np.random number
  uniform / standard normal no genration
  
  
Day-3
matplot.lib
sunbun
csv
html
jason

   
   

In [1]:
import numpy as np

arr=([1,2,3,4,5])

arr

 ##'this is not make array; it forms list.'
 ##and list size check  we have to use len function' 
type(arr)  
len(arr)

array=np.array([1,2,3,4,5,6,7])
print(array)

type(array)

np.shape(array)


# tuple , Caution!

a_lst=(1,2,3,5)
a_lst

type(a_lst)

a_lst=[1,2,3,5]
type(a_lst)

a_lst=([1,2,3,5])
type(a_lst)

ar=np.array(a_lst)
ar

np.shape(ar)

type(ar)

b_lst=([1,2,3,4],[1,2,3,5])
b_lst

br=np.array(b_lst)
np.shape(br)
type(br)

br

b_lst

b_lst=[1,2,3,4]
c_lst=[10,25,3.2,88.9]
d_lst=[1.2,52,35,2]
e_lst=[5,6,7,8]
f_lst=[8,9,7,6]

print(d_lst)

[1 2 3 4 5 6 7]
[1.2, 52, 35, 2]


In [3]:
#we=np.array([[b_lst],[c_lst],[d_lst],[e_lst],[f_lst]])

we=np.array([b_lst,c_lst,d_lst,e_lst,f_lst])

In [4]:
# this 2d array bcz 2 sqre bracket strt and end #
# how multi dim form? #

we
#we.shape

# we stack this item but can't make lst even arryay.
e = [[1,2,3,4],
[10,25,3.2,88.9],
[1.2,52,35,2],
[5,6,7,8],
[8,9,7,6]]
e
type(e)
#np.shape(e)



f=np.array(e)
type(f)
f

np.shape(f)
#f.shape

e = (1,2,3,4,5,6,7,8,[8,9,7,6])
type(e)

e

e = [1,2,3,4,5,6,7,8,[8,9,7,6]]
e

type(e)

g=np.array(e)
type(g)
np.shape(g)

np.array(e)

type(d_lst)

br=np.array(b_lst)
type(br)
br

br=np.array([b_lst,c_lst,d_lst,e_lst,f_lst])
type(br)
br

br=np.array([b_lst,c_lst])

br

array([[ 1. ,  2. ,  3. ,  4. ],
       [10. , 25. ,  3.2, 88.9]])

##  creating number

In [4]:
for number in range(1,5):
    print(number)

for x in range(1,5):
  print(x)
       

for i in range(1,5):
    print(i)

for i in range(1) :
    print ((1,5), '\n',(2,5,2))

a_list = list(range(1, 3))

print(a_list)


print(*range(1,3)) 

###

list('tennumber')

type(list(range(1,10)))

abc =list(range(1,3))
abc


sum(abc)

np.mean(abc)

np.var(abc)

1
2
3
4
1
2
3
4
1
2
3
4
(1, 5) 
 (2, 5, 2)
[1, 2]
1 2


0.25

## Histogram plot


In [17]:
import matplotlib.pyplot as plt

plt.hist(abc)
plt.axvline(np.mean(abc), color='k', linestyle='-.', linewidth=1)
#plt.axvline(np.var(abc), color='r', linestyle=':', linewidth=1)

plt.hist(abc,bins=50)
plt.axvline(np.mean(abc), color='k', linestyle='-.', linewidth=1)
plt.axvline(np.var(abc), color='r', linestyle=':', linewidth=1)

In [5]:
#l=np.array(['576','635','558'])
l

array(['576', '635', '558'], dtype='<U3')

In [133]:
l=[576,635,558,578,666,580,555,661,651,605,653,575,545,572,594]
len(l)
np.mean(l)

600.2666666666667

In [134]:
g=[3.39,3.30,2.81,3.03,3.44,3.07,3.00,3.43,3.36,3.13,3.12,2.74,2.76,2.88,3.96]
len(g)

15

In [97]:
l[0:15]-np.mean(l)

array([-24.26666667,  34.73333333, -42.26666667, -22.26666667,
        65.73333333, -20.26666667, -45.26666667,  60.73333333,
        50.73333333,   4.73333333,  52.73333333, -25.26666667,
       -55.26666667, -28.26666667,  -6.26666667])

In [98]:
print("mean of l" ,np.mean(l))
print("mean of g", np.mean(g))


mean of l 600.2666666666667
mean of g 3.1613333333333333


In [112]:
theta=(sum((l[0:15]-np.mean(l))*(g[0:15]-np.mean(g))))/(math.sqrt(sum(((l[0:15]-np.mean(l))**2)*((g[0:15]-np.mean(g)))**2)))

In [113]:
theta

2.5006016661469483

In [114]:
import math
math.sqrt(sum(((l[0:15]-np.mean(l))**2)*((g[0:15]-np.mean(g)))**2))

41.731823216554744

In [115]:
theta=sum((l[0:15]-np.mean(l))*(g[0:15]-np.mean(g)))
theta

104.35466666666669

In [116]:
a=sum((l[0:15])-np.mean(l))
a

2.2737367544323206e-13

In [117]:
b=sum(g[0:15]-np.mean(g))
b

-4.440892098500626e-16

In [118]:
c=a*b
c

-1.0097419586828951e-28

In [119]:
d=sum(l[0:15]-np.mean(l))**2
d

5.169878828456423e-26

In [120]:
e=sum(g[0:15]-np.mean(g))**2
e




1.9721522630525295e-31

In [121]:
d*e

1.0195788231247695e-56

In [122]:
f =math.sqrt(d*e)
print(f)

1.0097419586828951e-28


In [123]:
i= (c) / (f)
i

-1.0

#### sample coreelation 

In [124]:

theta=(sum((l[0:15])-np.mean(l))*sum(g[0:15]-np.mean(g))) / math.sqrt((sum(l[0:15]-np.mean(l))**2)* (sum(g[0:15]-np.mean(g))**2))

 
print(theta)    

-1.0


In [ ]:
#sum l[0:15]-np.mean(l)* g[0:15]-np.mean(g)

In [132]:
sum(l[0:15]-np.mean(l))*(g[0:15]-np.mean(g))

array([ 5.19927805e-14,  3.15291497e-14, -7.98839513e-14, -2.98617427e-14,
        6.33614642e-14, -2.07667957e-14, -3.66829530e-14,  6.10877275e-14,
        4.51715702e-14, -7.12437516e-15, -9.39811192e-15, -9.58001086e-14,
       -9.12526351e-14, -6.39677940e-14,  1.81595775e-13])

In [131]:
104.35466666666669 /  1.0097419586828951e-28

1.033478561223569e+30

In [137]:
l


[576, 635, 558, 578, 666, 580, 555, 661, 651, 605, 653, 575, 545, 572, 594]

In [138]:
g

[3.39,
 3.3,
 2.81,
 3.03,
 3.44,
 3.07,
 3.0,
 3.43,
 3.36,
 3.13,
 3.12,
 2.74,
 2.76,
 2.88,
 3.96]

In [135]:
l[1]+l[2]

1193

In [136]:
l[1]+g[1]

638.3

In [147]:
l[0]-np.mean(l) * g[0]-np.mean(g)

-1462.0653333333332

In [140]:
type(l[1])

int

In [153]:
sum((l[0:15]-np.mean(l)) * (g[0:15]-np.mean(g)))

104.35466666666669

In [156]:
(l[0]-np.mean(l)) * (g[0]-np.mean(g)) + ((l[1]-np.mean(l)) * (g[1]-np.mean(g)))

-0.7326222222222256

In [158]:
(l[1]-np.mean(l)) * (g[1]-np.mean(g))

4.8163555555555515

In [159]:
(l[0]-np.mean(l)) * (g[0]-np.mean(g))

-5.548977777777777

In [160]:
-5.548977777777777 + 4.8163555555555515


-0.7326222222222256